language: ruby
sudo: false
script: bundle exec rake test
matrix:
  fast_finish: true
  include:
  - rvm: 2.0
    gemfile: Gemfile
  - rvm: 2.1
    gemfile: Gemfile
  - rvm: 2.2
    gemfile: Gemfile
  - rvm: 2.3
    gemfile: Gemfile
  - rvm: 2.4
    gemfile: Gemfile
  - rvm: jruby-head
    gemfile: Gemfile
  allow_failures:
  - rvm: jruby-head
